application: gea-wtforms
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /static/
    static_dir: static/
    secure: always
    http_headers:
      X-Frame-Options: "DENY"
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"

  - url: /.*
    script: wsgi.app

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: latest
